import './style.css';
import {dateKey,timeKey,londonTimestamp,pretty} from './time.js';
const icon=path=>`<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const icons={calendar:icon('<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5h1m6 0h1"/>'),list:icon('<path d="M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1"/>'),map:icon('<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>')};
const state={viewings:[],mode:'calendar',month:new Date(`${dateKey(Date.now()).slice(0,7)}-01T12:00:00Z`),selected:dateKey(Date.now()),push:false,filter:'upcoming',search:''};
let installPrompt;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#install')?.classList.remove('hidden');});
const app=document.querySelector('#app');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const progressOf=v=>({intent:'undecided',attendance:v.status==='viewed'?'attended':'pending',email:false,application:false,documents:false,references:false,offer:false,agreement:false,deposit:false,keys:false,outcome:'ongoing',...v.progress});
const progressLabel=v=>{const p=progressOf(v);return p.outcome!=='ongoing'?({secured:'Property secured',unsuccessful:'Unsuccessful',withdrawn:'Withdrawn'}[p.outcome]):p.attendance==='attended'?'Attended':p.attendance==='missed'?'Not attended':p.intent==='no'?'Will not attend':p.intent==='yes'?'Will attend':v.status;};
const maps=a=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a)}`;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4500);}
async function api(path,options={}) {const res=await fetch(`/api${path}`,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await res.json();if(!res.ok){if(res.status===401&&!path.includes('login'))login();throw new Error(data.error||'Request failed.');}return data;}
const send=(path,data,method='POST')=>api(path,{method,body:JSON.stringify(data)});
async function refresh(){state.viewings=await api('/viewings');render();}
function login(configured=true){app.innerHTML=`<main class="login"><div class="brand"><span class="brand-icon">⌂</span> Viewing Tracker</div><section class="login-card"><h1>Welcome back.</h1><p>Sign in to your private viewing calendar.</p><form id="login"><label>App password<input name="password" type="password" autocomplete="current-password" required autofocus></label><p class="error" id="login-error" role="alert"></p><button class="primary" ${configured?'':'disabled'}>Open my viewings</button></form>${configured?'':'<p>Server setup is needed. Configure the app password before signing in.</p>'}</section><small>Private calendar · Six-hour reminders</small></main>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{await send('/login',{password:new FormData(e.target).get('password')});await refresh();await syncPush();}catch(err){document.querySelector('#login-error').textContent=err.message;}finally{btn.disabled=false;}};}
function header(){return `<aside class="sidebar"><div class="brand"><span class="brand-icon">⌂</span><span>Viewing<br>Tracker</span></div><div class="nav-label">YOUR SPACE</div><nav>${['calendar','agenda','locations'].map(m=>`<button data-mode="${m}" class="nav-item ${state.mode===m?'active':''}"><span>${icons[m==='agenda'?'list':m==='locations'?'map':'calendar']}</span>${m[0].toUpperCase()+m.slice(1)}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="reminder-note"><span class="mini-icon">◷</span><b>Six-hour reminders</b><button class="text-button" id="reminders">${state.push?'Manage reminders':'Enable reminders'}</button></div><button class="nav-item ${installPrompt?'':'hidden'}" id="install">↓ Install app</button><button class="nav-item" id="signout">Sign out</button></div></aside>`;}
function render(){
 const upcoming=state.viewings.filter(v=>v.status==='scheduled'&&v.starts_at>=Date.now()&&progressOf(v).intent!=='no'&&progressOf(v).outcome==='ongoing');const next=upcoming[0];
 app.innerHTML=`<div class="shell">${header()}<main class="main"><header class="topbar"><span class="breadcrumb">My viewings <span>/</span> ${state.mode[0].toUpperCase()+state.mode.slice(1)}</span><button class="reminder-pill" id="push-status"><span class="status-dot ${state.push?'on':''}"></span>${state.push?'Reminders on':'Enable reminders'}</button></header><section class="page-heading"><div><h1>Your viewings</h1></div><button class="primary" id="add"><span>+</span> Add viewing</button></section><div class="summary"><div><span class="summary-label">UPCOMING</span><strong>${upcoming.length}<small>viewing${upcoming.length===1?'':'s'} planned</small></strong></div><div><span class="summary-label">NEXT VIEWING</span><button class="next-summary" ${next?`data-open="${next.id}"`: 'disabled'}>${next?escape(pretty(next.starts_at,{weekday:'short',day:'numeric',month:'short'})):'Nothing booked yet'}<small>${next?`${timeKey(next.starts_at)} · ${escape(next.title)}`:'Add your first viewing to get started'}</small></button></div><div class="timezone"><span>◷</span><div>UK local time<small>Europe / London</small></div></div></div><div class="workspace">${state.mode==='calendar'?calendar():state.mode==='agenda'?agenda():locations()}</div><footer>All viewing times are shown in UK local time.</footer></main><nav class="mobile-nav">${['calendar','agenda','locations'].map(m=>`<button data-mode="${m}" class="${state.mode===m?'active':''}"><span>${icons[m==='agenda'?'list':m==='locations'?'map':'calendar']}</span>${m[0].toUpperCase()+m.slice(1)}</button>`).join('')}</nav></div>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render();});
 document.querySelector('#add').onclick=()=>form();
 document.querySelector('#reminders').onclick=notificationSettings;document.querySelector('#push-status').onclick=notificationSettings;
 document.querySelector('#signout').onclick=async()=>{try{await send('/logout',{});state.viewings=[];login();}catch(e){toast(e.message);}};
 document.querySelector('#install').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;render();};
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();details(b.dataset.open);});
 document.querySelectorAll('.calendar-event[data-open]').forEach(b=>b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();details(b.dataset.open);}});
 document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.day;render();const entries=state.viewings.filter(v=>dateKey(v.starts_at)===state.selected&&v.status!=='cancelled');if(entries.length===1)details(entries[0].id);});
 document.querySelectorAll('[data-day]').forEach(b=>b.onkeydown=e=>{if(e.target===b&&(e.key==='Enter'||e.key===' ')){e.preventDefault();b.click();}});
 document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{state.month.setUTCMonth(state.month.getUTCMonth()+Number(b.dataset.month));render();});
 document.querySelector('#today')?.addEventListener('click',()=>{state.selected=dateKey(Date.now());state.month=new Date(`${state.selected.slice(0,7)}-01T12:00Z`);render();});
 document.querySelector('#add-day')?.addEventListener('click',()=>form(null,state.selected));
 document.querySelector('#filter')?.addEventListener('change',e=>{state.filter=e.target.value;render();});
 document.querySelector('#search')?.addEventListener('input',e=>{state.search=e.target.value;const holder=document.createElement('div');holder.innerHTML=agenda();document.querySelector('#agenda-results').innerHTML=holder.querySelector('#agenda-results').innerHTML;document.querySelectorAll('#agenda-results [data-open]').forEach(b=>b.onclick=()=>details(b.dataset.open));});
 document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>{state.mapId=b.dataset.location;render();});
}
function calendar(){const year=state.month.getUTCFullYear(),month=state.month.getUTCMonth();const first=new Date(Date.UTC(year,month,1)),offset=(first.getUTCDay()+6)%7;const days=new Date(Date.UTC(year,month+1,0)).getUTCDate();const count=Math.ceil((offset+days)/7)*7;const today=dateKey(Date.now());const grouped=new Map();for(const v of state.viewings){const key=dateKey(v.starts_at);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(v);}let cells='';
 for(let i=0;i<count;i++){const d=new Date(Date.UTC(year,month,1+i-offset,12));const key=d.toISOString().slice(0,10);const entries=(grouped.get(key)||[]).filter(v=>v.status!=='cancelled');cells+=`<div class="day ${d.getUTCMonth()===month?'':'muted'} ${key===state.selected?'selected':''} ${key===today?'today':''}" data-day="${key}" role="button" tabindex="0" aria-label="${key}, ${entries.length} viewings" aria-pressed="${key===state.selected}"><span class="day-number">${d.getUTCDate()}</span><div class="day-events">${entries.slice(0,2).map(v=>`<span data-open="${v.id}" role="button" tabindex="0" aria-label="Open ${escape(v.title)}" class="calendar-event ${v.status==='viewed'?'viewed':''}"><b>${timeKey(v.starts_at)}</b> <span>${escape(v.title)}</span></span>`).join('')}${entries.length>2?`<small>+${entries.length-2} more</small>`:''}</div>${entries.length?`<span class="mobile-dots">${entries.slice(0,3).map(()=>'<i></i>').join('')}</span>`:''}</div>`;}
 const selected=grouped.get(state.selected)||[];
 return `<section class="calendar-panel panel"><div class="panel-head"><h2>${pretty(state.month,{month:'long',year:'numeric'})}</h2><div class="month-controls"><button id="today">Today</button><button data-month="-1" aria-label="Previous month">‹</button><button data-month="1" aria-label="Next month">›</button></div></div><div class="weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${cells}</div><div class="calendar-legend"><span><i></i> Viewing</span><span>Choose a day to see details</span></div></section><aside class="day-panel panel"><div class="day-heading"><span class="eyebrow">${state.selected===today?'TODAY':'SELECTED DAY'}</span><h2>${pretty(new Date(`${state.selected}T12:00Z`),{weekday:'long'})}</h2><p>${pretty(new Date(`${state.selected}T12:00Z`),{day:'numeric',month:'long',year:'numeric'})}</p></div>${selected.length?selected.map(card).join(''):`<div class="empty"><div class="empty-icon">▦</div><h3>No viewings this day</h3><p>Choose another date or add a viewing.</p></div>`}<button class="secondary full" id="add-day">+ Add a viewing this day</button></aside>`;
}
function card(v){return `<article class="viewing-card ${v.status==='cancelled'?'cancelled':''}"><div class="card-top"><span class="time">${timeKey(v.starts_at)}<small> · ${v.duration} min</small></span><span class="badge ${v.status}">${escape(progressLabel(v))}</span></div><button class="card-title" data-open="${v.id}">${escape(v.title)}</button><a class="address" href="${maps(v.address)}" target="_blank" rel="noopener">⌖ ${escape(v.address)}</a>${v.agent?`<div class="agent">${escape(v.agent)}</div>`:''}<button class="text-button" data-open="${v.id}">Details</button></article>`;}
function agenda(){let list=state.viewings.filter(v=>state.filter==='all'||(state.filter==='upcoming'?v.status==='scheduled'&&v.starts_at>=Date.now():v.starts_at<Date.now()||v.status!=='scheduled'));list=list.filter(v=>!state.search||`${v.title} ${v.address} ${v.agent}`.toLowerCase().includes(state.search.toLowerCase()));return `<section class="panel agenda-panel"><div class="panel-head"><h2>Viewing agenda</h2><select id="filter" aria-label="Filter viewings">${['upcoming','past','all'].map(f=>`<option ${state.filter===f?'selected':''} value="${f}">${f[0].toUpperCase()+f.slice(1)}</option>`).join('')}</select></div><label class="agenda-search">Search properties<input id="search" type="search" placeholder="Address, property or agent" value="${escape(state.search)}"></label><div id="agenda-results">${list.length?list.map(v=>`<div class="agenda-row"><div class="agenda-date"><b>${pretty(v.starts_at,{day:'2-digit'})}</b><span>${pretty(v.starts_at,{month:'short',weekday:'short'})}</span></div>${card(v)}</div>`).join(''):'<div class="empty"><div class="empty-icon">☷</div><h3>No matching viewings</h3><p>Try another filter or add a viewing.</p></div>'}</div></section>`;}
function propertyFacts(v){const p=v.property_details||{};const route=(minutes,direct)=>minutes==null?'Not entered':`${minutes} min · ${direct?'Direct':'Changes / indirect'}`;return `<section class="property-facts"><h3>Rent & travel</h3><dl><dt>Monthly rent</dt><dd>${p.rent==null?'Not entered':escape(new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(p.rent))+' / month'}</dd><dt>To office</dt><dd>${route(p.office_minutes,p.office_direct)}</dd><dt>To airport</dt><dd>${route(p.airport_minutes,p.airport_direct)}</dd></dl></section>`;}
function propertyFields(v){const p=v?.property_details||{};return `<section class="property-fields"><h3>Rent & travel</h3><label>Monthly rent · £<input type="number" name="rent" min="0" max="100000" step="0.01" placeholder="e.g. 725" value="${escape(p.rent)}"></label><div class="form-row"><div><label>Travel to office · minutes<input type="number" name="office_minutes" min="0" max="1440" step="1" placeholder="e.g. 45" value="${escape(p.office_minutes)}"></label><label class="route-check"><input type="checkbox" name="office_direct" ${p.office_direct?'checked':''}>Direct route to office</label></div><div><label>Travel to airport · minutes<input type="number" name="airport_minutes" min="0" max="1440" step="1" placeholder="e.g. 30" value="${escape(p.airport_minutes)}"></label><label class="route-check"><input type="checkbox" name="airport_direct" ${p.airport_direct?'checked':''}>Direct route to airport</label></div></div><p class="hint">One-way journey time. Tick direct when no changes are needed.</p></section><label>Notes<textarea name="notes" rows="3" maxlength="5000" placeholder="Travel routes, airport name, bills, questions…">${escape(v?.notes)}</textarea></label>`;}
function locations(){const list=state.viewings.filter(v=>v.status!=='cancelled');const selected=list.find(v=>v.id===state.mapId)||list.find(v=>v.starts_at>=Date.now())||list[0];return `<section class="panel locations-panel"><div class="panel-head"><h2>Your viewing locations</h2><span class="muted-text">${list.length} places</span></div>${selected?`<div class="map-layout"><div class="location-list">${list.map(v=>`<button data-location="${v.id}" class="location-item ${v.id===selected.id?'active':''}"><b>${escape(v.title)}</b><span>${escape(v.address)}</span><small>${pretty(v.starts_at,{day:'numeric',month:'short'})} · ${timeKey(v.starts_at)}</small></button>`).join('')}</div><div class="map-content"><iframe title="Map of ${escape(selected.address)}" src="https://maps.google.com/maps?q=${encodeURIComponent(selected.address)}&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-caption"><div><b>${escape(selected.title)}</b><p>${escape(selected.address)}</p></div><button class="secondary" data-open="${selected.id}">Details & edit</button><a class="secondary" href="${maps(selected.address)}" target="_blank" rel="noopener">Google Maps ↗</a></div>${propertyFacts(selected)}${selected.notes?`<h3>Notes</h3><p class="notes">${escape(selected.notes)}</p>`:''}</div></div>`:'<div class="empty"><div class="empty-icon">⌖</div><h3>Put your next place on the map</h3><p>Add a viewing to see its location here.</p></div>'}</section>`;}
function modal(html){document.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.innerHTML=html;document.body.append(d);d.showModal();d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());d.addEventListener('close',()=>{d.remove();if(state.viewings.length)render();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});return d;}
function details(id){const v=state.viewings.find(v=>v.id===id);if(!v)return;const d=modal(`<div class="modal-head"><span class="eyebrow">VIEWING DETAILS</span><button data-close aria-label="Close">×</button></div><h2>${escape(v.title)}</h2><p class="detail-time">${pretty(v.starts_at,{weekday:'long',day:'numeric',month:'long'})} · ${timeKey(v.starts_at)} <small>UK time</small></p><div class="detail-address"><a href="${maps(v.address)}" target="_blank" rel="noopener">⌖ ${escape(v.address)} ↗</a><button id="copy" class="secondary">Copy address</button></div><details class="map-disclosure"><summary>Show map</summary><div data-map-address="${escape(v.address)}"></div></details><dl><dt>Status</dt><dd>${escape(progressLabel(v))}</dd><dt>Duration</dt><dd>${v.duration} minutes</dd>${v.agent?`<dt>Agent</dt><dd>${escape(v.agent)}</dd>`:''}${v.contact?`<dt>Contact</dt><dd>${escape(v.contact)}</dd>`:''}</dl>${v.links.length?`<div class="detail-links">${v.links.map((l,i)=>`<a href="${escape(l)}" target="_blank" rel="noopener">Property link ${i+1} ↗</a>`).join('')}</div>`:''}${propertyFacts(v)}${v.notes?`<h3>Notes</h3><p class="notes">${escape(v.notes)}</p>`:''}${workflow(v)}<p class="hint">Reminder: ${pretty(v.starts_at-21600000,{day:'numeric',month:'short'})} at ${timeKey(v.starts_at-21600000)} UK time.</p><div class="modal-actions"><button id="delete" class="danger">Delete</button><button id="edit" class="primary">Edit viewing</button></div>`);
 bindWorkflow(d,v);
 d.querySelector('.map-disclosure').ontoggle=e=>{const host=e.target.querySelector('[data-map-address]');if(e.target.open&&!host.firstChild){const frame=document.createElement('iframe');frame.className='detail-map';frame.title=`Map of ${v.address}`;frame.src=`https://maps.google.com/maps?q=${encodeURIComponent(v.address)}&output=embed`;host.append(frame);}};
 d.querySelector('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(v.address);toast('Address copied');}catch{toast('Select the address text to copy it.');}};
 d.querySelector('#edit').onclick=()=>form(v);
 d.querySelector('#delete').onclick=()=>{const c=modal(`<div class="modal-head"><h2>Delete this viewing?</h2><button data-close aria-label="Close">×</button></div><p>${escape(v.title)} will be removed and its future reminder cancelled.</p><div class="modal-actions"><button class="secondary" data-cancel>Keep viewing</button><button class="danger" data-confirm>Delete viewing</button></div>`);c.querySelector('[data-cancel]').onclick=()=>details(id);c.querySelector('[data-confirm]').onclick=async()=>{try{await api(`/viewings/${id}`,{method:'DELETE'});c.close();await refresh();toast('Viewing deleted');}catch(e){toast(e.message);}};};
}
function workflow(v){const p=progressOf(v),ended=Date.now()>=v.starts_at+v.duration*60000;
 const options=(items,value)=>items.map(([key,label])=>`<option value="${key}" ${key===value?'selected':''}>${label}</option>`).join('');
 return `<section class="workflow"><h3>Attendance & property progress</h3><label>Plans for this viewing<select data-progress="intent">${options([['undecided','Undecided'],['yes','Will attend'],['no','Will not attend']],p.intent)}</select></label><label>Viewing attendance<select data-progress="attendance" ${ended?'':'disabled'}>${options([['pending','Not recorded'],['attended','Attended'],['missed','Not attended']],p.attendance)}</select></label>${ended?'':'<p class="hint">Record attendance after the viewing finishes.</p>'}${p.attendance==='attended'?`<h3>Next steps <small>${['email','application','documents','references','offer','agreement','deposit','keys'].filter(k=>p[k]).length}/8 done</small></h3><p class="hint">Tick steps as you complete them.</p><div class="progress-checklist">${[['email','Follow-up email sent'],['application','Application submitted'],['documents','Documents sent'],['references','References approved'],['offer','Offer accepted'],['agreement','Tenancy agreement signed'],['deposit','Deposit paid'],['keys','Keys received']].map(([key,label])=>`<label><input type="checkbox" data-progress="${key}" ${p[key]?'checked':''}>${label}</label>`).join('')}</div>`:''}<label>Property outcome<select data-progress="outcome">${options([['ongoing','In progress'],['secured','Property secured'],['unsuccessful','Unsuccessful'],['withdrawn','Withdrawn']],p.outcome)}</select></label><p class="hint">${p.intent==='no'?'Viewing reminders are off for this property.':''}</p><p class="error" role="alert" id="progress-error"></p></section>`;
}
function bindWorkflow(d,v){d.querySelectorAll('[data-progress]').forEach(el=>el.onchange=async()=>{const p=progressOf(v);p[el.dataset.progress]=el.type==='checkbox'?el.checked:el.value;const status=p.attendance==='pending'?(v.status==='viewed'?'scheduled':v.status):'viewed';d.querySelectorAll('[data-progress]').forEach(x=>x.disabled=true);try{await send(`/viewings/${v.id}`,{...v,status,progress:p},'PUT');v.progress=p;v.status=status;v.revision+=1;const scroll=d.scrollTop;const active=el.dataset.progress;d.querySelector('.workflow').outerHTML=workflow(v);bindWorkflow(d,v);d.scrollTop=scroll;d.querySelector(`[data-progress="${active}"]`)?.focus({preventScroll:true});d.querySelector('dl dd').textContent=progressLabel(v);toast('Saved');}catch(e){d.querySelector('#progress-error').textContent=e.message;d.querySelectorAll('[data-progress]').forEach(x=>x.disabled=false);if(el.type==='checkbox')el.checked=progressOf(v)[el.dataset.progress];else el.value=progressOf(v)[el.dataset.progress];}});}
function form(v=null,date=dateKey(Date.now())){const d=modal(`<div class="modal-head"><div><h2>${v?'Edit viewing':'Add a viewing'}</h2></div><button data-close aria-label="Close">×</button></div><form id="viewing-form"><label>Property name<input name="title" placeholder="e.g. Two-bed flat in Musselburgh" maxlength="120" value="${escape(v?.title)}" required></label><label>Address<input name="address" placeholder="Street, town and postcode" maxlength="500" value="${escape(v?.address)}" required></label><div class="form-row"><label>Date<input type="date" name="date" value="${v?dateKey(v.starts_at):date}" required></label><label>Time · UK<input type="time" name="time" value="${v?timeKey(v.starts_at):'14:00'}" required></label></div><div class="form-row"><label>Duration<select name="duration">${[15,20,30,45,60,90,120,...(v&&![15,20,30,45,60,90,120].includes(v.duration)?[v.duration]:[])].map(n=>`<option value="${n}" ${n===(v?.duration||30)?'selected':''}>${n} minutes</option>`).join('')}</select></label><label>Status<select name="status">${['scheduled','viewed','cancelled'].map(s=>`<option value="${s}" ${s===v?.status?'selected':''}>${s[0].toUpperCase()+s.slice(1)}</option>`).join('')}</select></label></div>${propertyFields(v)}<div class="reminder-info">◷ Reminder 6 hours before · enable reminders on your device</div><details ${v?'open':''}><summary>Agent & property links <span>Optional</span></summary><label>Letting agent<input name="agent" maxlength="200" value="${escape(v?.agent)}" placeholder="Agent or landlord name"></label><label>Contact details<input name="contact" maxlength="200" value="${escape(v?.contact)}" placeholder="Phone or email"></label><label>Property links<textarea name="links" rows="2" placeholder="https://… (one link per line)">${escape(v?.links.join('\n'))}</textarea></label></details><p id="form-error" class="error" role="alert"></p><div class="modal-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary" type="submit">${v?'Save changes':'Save viewing'}</button></div></form>`);
 d.querySelector('#cancel').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{const f=Object.fromEntries(new FormData(e.target));const payload={...f,starts_at:londonTimestamp(f.date,f.time),duration:Number(f.duration),links:f.links.split('\n').map(s=>s.trim()).filter(Boolean),property_details:{rent:f.rent===''?null:Number(f.rent),office_minutes:f.office_minutes===''?null:Number(f.office_minutes),airport_minutes:f.airport_minutes===''?null:Number(f.airport_minutes),office_direct:f.office_direct==='on',airport_direct:f.airport_direct==='on'},revision:v?.revision,progress:v?progressOf(v):undefined};await send(v?`/viewings/${v.id}`:'/viewings',payload,v?'PUT':'POST');state.selected=f.date;state.month=new Date(`${f.date.slice(0,7)}-01T12:00Z`);d.close();await refresh();toast('Viewing saved');}catch(err){d.querySelector('#form-error').textContent=err.message;}finally{btn.disabled=false;}};
}
async function syncPush(){try{if(!('serviceWorker' in navigator)||!('PushManager' in window))return;const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();state.push=!!sub&&Notification.permission==='granted';if(state.push)await send('/push/subscriptions',sub.toJSON());render();}catch{state.push=false;render();}}
async function enablePush(){if(!('serviceWorker' in navigator)||!('PushManager' in window))throw new Error('Push notifications are not supported here. Use Chrome on Android.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Allow notifications in your browser’s site settings, then try again.');const {key}=await api('/push/key');const bytes=Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await send('/push/subscriptions',sub.toJSON());state.push=true;render();}
function notificationSettings(){const d=modal(`<div class="modal-head"><h2>Viewing reminders</h2><button data-close aria-label="Close">×</button></div><div class="notification-hero">◷<h3>A heads-up, six hours ahead.</h3><p>Receive the time and address, even when this app is closed.</p></div><p>Allow notifications and turn on sound in your phone’s notification settings. Alerts cannot override silent mode or Do Not Disturb.</p><p class="hint">Added a viewing less than six hours away? Its reminder will be sent on the next scheduled check. Internet access is needed for delivery.</p><p id="push-error" class="error" role="alert"></p><div class="notification-actions"><button class="primary" id="enable">${state.push?'Test notification':'Enable on this device'}</button>${state.push?'<button class="secondary" id="disable">Turn off on this device</button>':''}</div><p class="hint">Install on Android: Chrome menu → Add to Home screen → Install.</p><button class="text-button" id="mobile-signout">Sign out of this device</button>`);
 d.querySelector('#mobile-signout').onclick=async()=>{try{await send('/logout',{});state.viewings=[];d.close();login();}catch(e){toast(e.message);}};
 d.querySelector('#enable').onclick=async e=>{e.target.disabled=true;try{if(!state.push){await enablePush();d.close();notificationSettings();toast('Reminders enabled');}else{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();await send('/push/test',{endpoint:sub?.endpoint});toast('Test notification sent');}}catch(err){d.querySelector('#push-error').textContent=err.message;}finally{e.target.disabled=false;}};
 d.querySelector('#disable')?.addEventListener('click',async()=>{try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub){await send('/push/subscriptions',{endpoint:sub.endpoint},'DELETE');await sub.unsubscribe();}state.push=false;d.close();render();toast('Reminders turned off on this device');}catch(e){toast(e.message);}});
}
async function boot(){app.innerHTML='<main class="loading">Opening your viewing calendar…</main>';try{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>toast('App installation is unavailable in this browser.'));const s=await api('/session');if(!s.authenticated){login(s.configured);return;}await refresh();await syncPush();const id=new URL(location.href).searchParams.get('viewing');if(id)details(id);}catch(e){app.innerHTML='<main class="loading"><h1>Unable to connect</h1><p>Check your connection and reload to open your calendar.</p><button class="primary" id="retry">Try again</button></main>';document.querySelector('#retry').onclick=boot;toast(e.message);}}
window.addEventListener('online',()=>toast('Back online. Refresh to load your latest viewings.'));
window.addEventListener('offline',()=>toast('You’re offline. Connect to save changes.'));
boot();
